language: java
jdk:
  - oraclejdk8
before_script: 
  cd spring-boot-reactive-web
addons:
  sonarcloud:
    organization: "thepracticaldeveloper"
    branches:
      - master
      - develop
script:
  - mvn clean install sonar:sonar